version: '3.1'

services:
  db:
    build: .
    container_name: ccb-api-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ccb
